.github/workflows/ci.yml
removed gradle version check in CI to prevent breaking on unit tests
=> removed gradle version check in CI

opensrp-ecap-chw/build.gradle, opensrp-ecap-chw/src/main/java/com/bluecodeltd/ecap/chw/fragment/FamilyRegisterFragment.java
=> Update dependencies to use packages from GitHub Package Registry

opensrp-ecap-chw/src/ecap/assets/ec_client_fields.json, opensrp-ecap-chw/src/ecap/assets/json.form/family_register.json
All fields up to date and saving successfully
=> Update Household form

opensrp-ecap-chw/src/ecap/assets/json.form/child_index.json, opensrp-ecap-chw/src/ecap/assets/json.form/mother_index.json, opensrp-ecap-chw/src/main/java/com/bluecodeltd/ecap/chw/activity/IdentificationRegisterActivity.java, opensrp-ecap-chw/src/main/java/com/bluecodeltd/ecap/chw/contract/IdentificationRegisterContract.java, opensrp-ecap-chw/src/main/java/com/bluecodeltd/ecap/chw/contract/IdentificationRegisterFragmentContract.java, opensrp-ecap-chw/src/main/java/com/bluecodeltd/ecap/chw/fragment/IdentificationFragmentRegister.java, opensrp-ecap-chw/src/main/java/com/bluecodeltd/ecap/chw/interactor/IdentificationRegisterInteractor.java, opensrp-ecap-chw/src/main/java/com/bluecodeltd/ecap/chw/model/IdentificationEventClient.java, opensrp-ecap-chw/src/main/java/com/bluecodeltd/ecap/chw/model/IdentificationRegisterModel.java, opensrp-ecap-chw/src/main/java/com/bluecodeltd/ecap/chw/presenter/IdentificationRegisterFragmentPresenter.java, opensrp-ecap-chw/src/main/java/com/bluecodeltd/ecap/chw/presenter/IdentificationRegisterPresenter.java, opensrp-ecap-chw/src/main/java/com/bluecodeltd/ecap/chw/util/Constants.java
Implementation of Register excluding the required forms
=> Create Identification Register

opensrp-ecap-chw/build.gradle, opensrp-ecap-chw/src/ecap/assets/json.form/female_sex_worker.json, opensrp-ecap-chw/src/ecap/assets/json.form/vca_screening.json, opensrp-ecap-chw/src/ecap/java/com/bluecodeltd/ecap/chw/model/NavigationModelFlv.java, opensrp-ecap-chw/src/ecap/res/values/strings.xml, opensrp-ecap-chw/src/main/AndroidManifest.xml, opensrp-ecap-chw/src/main/java/com/bluecodeltd/ecap/chw/activity/FamilyRegisterActivity.java, opensrp-ecap-chw/src/main/java/com/bluecodeltd/ecap/chw/activity/IdentificationRegisterActivity.java, opensrp-ecap-chw/src/main/java/com/bluecodeltd/ecap/chw/activity/IndexRegisterActivity.java, opensrp-ecap-chw/src/main/java/com/bluecodeltd/ecap/chw/application/ChwApplication.java, opensrp-ecap-chw/src/main/java/com/bluecodeltd/ecap/chw/custom_view/AlertDialogForIndexRegistrationRegister.java, opensrp-ecap-chw/src/main/java/com/bluecodeltd/ecap/chw/listener/ChwBottomNavigationListener.java, opensrp-ecap-chw/src/main/java/com/bluecodeltd/ecap/chw/presenter/IdentificationRegisterFragmentPresenter.java, opensrp-ecap-chw/src/main/java/com/bluecodeltd/ecap/chw/util/Constants.java, opensrp-ecap-chw/src/main/res/menu/bottom_nav_menu.xml, opensrp-ecap-chw/src/main/res/values/colors.xml, opensrp-ecap-chw/src/main/res/values/strings.xml, opensrp-ecap-chw/src/main/res/values/styles.xml
Updated Navigation, Menu Options and Dialogue Box
=> App navigation

opensrp-ecap-chw/src/ecap/assets/ec_client_fields.json, opensrp-ecap-chw/src/ecap/assets/json.form/vca_screening.json, opensrp-ecap-chw/src/main/java/com/bluecodeltd/ecap/chw/activity/IndexDetailsActivity.java, opensrp-ecap-chw/src/main/java/com/bluecodeltd/ecap/chw/fragment/IndexFragmentRegister.java
Displays Index name on profile page on index click, and fixed consent issue.
=> Index Name | Consent Message

opensrp-ecap-chw/build.gradle, opensrp-ecap-chw/src/ecap/assets/ec_client_classification.json, opensrp-ecap-chw/src/ecap/assets/ec_client_fields.json, opensrp-ecap-chw/src/ecap/assets/json.form/family_register.json, opensrp-ecap-chw/src/ecap/assets/json.form/vca_screening.json, opensrp-ecap-chw/src/ecap/assets/rule/vca_screening_calculation.yml, opensrp-ecap-chw/src/ecap/assets/rule/vca_screening_relevance.yml, opensrp-ecap-chw/src/main/java/com/bluecodeltd/ecap/chw/activity/IndexRegisterActivity.java
=> Skip Logic

.gitignore, opensrp-ecap-chw/src/ecap/assets/ec_client_fields.json, opensrp-ecap-chw/src/ecap/res/xml/authenticator.xml, opensrp-ecap-chw/src/main/java/com/bluecodeltd/ecap/chw/application/ChwSyncConfiguration.java, opensrp-ecap-chw/src/main/java/com/bluecodeltd/ecap/chw/interactor/LoginJobSchedulerProvider.java, opensrp-ecap-chw/src/main/java/com/bluecodeltd/ecap/chw/job/ChwJobCreator.java, opensrp-ecap-chw/src/main/java/com/bluecodeltd/ecap/chw/presenter/IndexRegisterFragmentPresenter.java
Update EC Client Fields and Query for Index Register
=> Update ec client fields

opensrp-ecap-chw/build.gradle
=> Working Login

opensrp-ecap-chw/src/ecap/assets/json.form/vca_screening.json
VCA Age and Caregiver Age Swap Fixed
=> Update Age Swap on SubPop form

opensrp-ecap-chw/src/ecap/assets/json.form/assessment.json, opensrp-ecap-chw/src/ecap/assets/rule/vca_vulnerability_assessment_relevance.yml
Resolved various issues for the alpha 6 release
=> Resolve issues in the alpha 6 release

opensrp-ecap-chw/src/ecap/assets/json.form/family_register_entry.json, opensrp-ecap-chw/src/main/java/com/bluecodeltd/ecap/chw/listener/ChwBottomNavigationListener.java
HH screening form launching from HH Register
=> HH screening form launching from HH Register

opensrp-ecap-chw/src/ecap/assets/json.form/family_register.json, opensrp-ecap-chw/src/main/java/com/bluecodeltd/ecap/chw/activity/IndexDetailsActivity.java
Additional Alpha 6 Issues resolved - Skip Logic Part D2
=> Alpha6 issues j1

opensrp-ecap-chw/src/ecap/assets/json.form/graduation_assessment_form.json, opensrp-ecap-chw/src/ecap/assets/json.form/graduation_assessment_sub_for_repeating_fields.json, opensrp-ecap-chw/src/ecap/assets/json.form/household_visitation_for_caregiver.json, opensrp-ecap-chw/src/ecap/assets/json.form/household_visitation_for_vca_0_20_years.json, opensrp-ecap-chw/src/main/java/com/bluecodeltd/ecap/chw/activity/IndexDetailsActivity.java, opensrp-ecap-chw/src/main/java/com/bluecodeltd/ecap/chw/util/Constants.java
Prefill the household visititation forms
=> Prefill the household visititation forms

opensrp-ecap-chw/src/ecap/assets/json.form/graduation_assessment_form.json, opensrp-ecap-chw/src/ecap/assets/json.form/graduation_assessment_sub_for_repeating_fields.json, opensrp-ecap-chw/src/ecap/assets/json.form/household_visitation_for_caregiver.json, opensrp-ecap-chw/src/ecap/assets/json.form/household_visitation_for_vca_0_20_years.json, opensrp-ecap-chw/src/main/java/com/bluecodeltd/ecap/chw/activity/IndexDetailsActivity.java, opensrp-ecap-chw/src/main/java/com/bluecodeltd/ecap/chw/util/Constants.java
Reverts BlueCodeSystems/opensrp-client-ecap-chw#363
=> Revert "Prefill the household visititation forms"

opensrp-ecap-chw/src/ecap/assets/ec_client_fields.json, opensrp-ecap-chw/src/ecap/assets/json.form/hiv_assessment.json, opensrp-ecap-chw/src/main/java/com/bluecodeltd/ecap/chw/activity/IndexDetailsActivity.java
- Remove unnecessary fields from risk assessment
- Add ec_client fields
=> Remove repetitive fields from risk assessment

opensrp-ecap-chw/src/ecap/assets/json.form/hh_enrollment.json, opensrp-ecap-chw/src/main/java/com/bluecodeltd/ecap/chw/activity/IndexDetailsActivity.java, opensrp-ecap-chw/src/main/java/com/bluecodeltd/ecap/chw/activity/IndexRegisterActivity.java, opensrp-ecap-chw/src/main/java/com/bluecodeltd/ecap/chw/dao/IndexPersonDao.java, opensrp-ecap-chw/src/main/java/com/bluecodeltd/ecap/chw/fragment/IndexFragmentRegister.java, opensrp-ecap-chw/src/main/java/com/bluecodeltd/ecap/chw/fragment/ProfileContactFragment.java, opensrp-ecap-chw/src/main/java/com/bluecodeltd/ecap/chw/fragment/ProfileOverviewFragment.java, opensrp-ecap-chw/src/main/java/com/bluecodeltd/ecap/chw/interactor/IndexRegisterInteractor.java, opensrp-ecap-chw/src/main/java/com/bluecodeltd/ecap/chw/model/Child.java, opensrp-ecap-chw/src/main/java/com/bluecodeltd/ecap/chw/presenter/IndexRegisterFragmentPresenter.java, opensrp-ecap-chw/src/main/java/com/bluecodeltd/ecap/chw/presenter/IndexRegisterPresenter.java
> Open child profile after registration
> Add toast to show when form is saved
=> Open child profile after registration

opensrp-ecap-chw/src/ecap/assets/json.form/vca_screening.json
Reverts BlueCodeSystems/opensrp-client-ecap-chw#471
=> Revert "Resolution of Issue #467, case status changed to radio buttons."

opensrp-ecap-chw/src/ecap/assets/json.form/caregiver_assessment.json, opensrp-ecap-chw/src/ecap/assets/json.form/child.json, opensrp-ecap-chw/src/ecap/assets/json.form/family_member.json, opensrp-ecap-chw/src/ecap/assets/json.form/family_register.json, opensrp-ecap-chw/src/ecap/assets/json.form/family_register_entry.json, opensrp-ecap-chw/src/ecap/assets/json.form/hh_member.json, opensrp-ecap-chw/src/ecap/assets/json.form/hh_screening_entry.json, opensrp-ecap-chw/src/ecap/assets/json.form/hiv_assessment.json, opensrp-ecap-chw/src/ecap/assets/json.form/hiv_risk_assessment_above_15_years.json, opensrp-ecap-chw/src/ecap/assets/json.form/hiv_risk_assessment_under_15_years.json, opensrp-ecap-chw/src/ecap/assets/json.form/initial_level_facility_form.json, opensrp-ecap-chw/src/ecap/assets/json.form/mother_index.json, opensrp-ecap-chw/src/ecap/assets/json.form/vca_assessment.json
New ART format which takes in a string of values e.g 0000-00000-000000-0
=> Update ART number

opensrp-ecap-chw/src/ecap/assets/json.form/caregiver_assessment.json, opensrp-ecap-chw/src/ecap/assets/json.form/child.json, opensrp-ecap-chw/src/ecap/assets/json.form/family_member.json, opensrp-ecap-chw/src/ecap/assets/json.form/family_register.json, opensrp-ecap-chw/src/ecap/assets/json.form/family_register_entry.json, opensrp-ecap-chw/src/ecap/assets/json.form/hh_member.json, opensrp-ecap-chw/src/ecap/assets/json.form/hh_screening_entry.json, opensrp-ecap-chw/src/ecap/assets/json.form/hiv_assessment.json, opensrp-ecap-chw/src/ecap/assets/json.form/hiv_risk_assessment_above_15_years.json, opensrp-ecap-chw/src/ecap/assets/json.form/hiv_risk_assessment_under_15_years.json, opensrp-ecap-chw/src/ecap/assets/json.form/initial_level_facility_form.json, opensrp-ecap-chw/src/ecap/assets/json.form/mother_index.json, opensrp-ecap-chw/src/ecap/assets/json.form/vca_assessment.json, opensrp-ecap-chw/src/main/java/com/bluecodeltd/ecap/chw/activity/IndexDetailsActivity.java, opensrp-ecap-chw/src/main/java/com/bluecodeltd/ecap/chw/fragment/HouseholdOverviewFragment.java, opensrp-ecap-chw/src/main/java/com/bluecodeltd/ecap/chw/fragment/HouseholdVisitsFragment.java, opensrp-ecap-chw/src/main/java/com/bluecodeltd/ecap/chw/fragment/ProfileOverviewFragment.java, opensrp-ecap-chw/src/main/java/com/bluecodeltd/ecap/chw/model/Household.java, opensrp-ecap-chw/src/main/res/layout/fragment_household_overview.xml
User should not be able to complete a case plan before HH screening, HH enrolment and HH Vulnerability assessment. #442
=> Create various issues branch

opensrp-ecap-chw/src/ecap/assets/json.form/family_member.json, opensrp-ecap-chw/src/ecap/assets/json.form/hh_screening_entry.json, opensrp-ecap-chw/src/main/java/com/bluecodeltd/ecap/chw/activity/HouseholdDetails.java, opensrp-ecap-chw/src/main/java/com/bluecodeltd/ecap/chw/activity/HouseholdIndexActivity.java, opensrp-ecap-chw/src/main/java/com/bluecodeltd/ecap/chw/activity/IndexRegisterActivity.java
Resolution of Issue123, phone number field keyboard now only shows
Resolution of Issue124, List of relationships to caregiver
Resolution of Issue126, display numbers only on fields in issue
=> J1 tasks branch

opensrp-ecap-chw/src/ecap/assets/ec_client_fields.json, opensrp-ecap-chw/src/ecap/assets/json.form/hh_screening_entry.json, opensrp-ecap-chw/src/main/java/com/bluecodeltd/ecap/chw/dao/HouseholdDao.java, opensrp-ecap-chw/src/main/java/com/bluecodeltd/ecap/chw/fragment/HouseholdOverviewFragment.java, opensrp-ecap-chw/src/main/java/com/bluecodeltd/ecap/chw/model/Household.java
-Editting  some fields of Household Screening Form
-Updated the EC Client fields of the Household Screening Form
-Updated the Household Dao to prefill the fields which were not able to pull data
-The field(Last Malaria Case) in the Household profile is able to pull data
=> The following issues have been resolved:

opensrp-ecap-chw/src/ecap/assets/ec_client_fields.json, opensrp-ecap-chw/src/ecap/assets/json.form/hh_screening_entry.json, opensrp-ecap-chw/src/ecap/assets/rule/hh_screening_relevance.yml
Correction of Emergency contact relationship.
Resolution of Issue515
=> Correction of Emergency contact relationship.

opensrp-ecap-chw/src/ecap/assets/json.form/vca_assessment.json, opensrp-ecap-chw/src/ecap/assets/rule/vca_assessment.yml, opensrp-ecap-chw/src/ecap/assets/rule/vca_vulnerability_assessment_relevance.yml, opensrp-ecap-chw/src/main/java/com/bluecodeltd/ecap/chw/activity/IndexDetailsActivity.java
-VCA Vulnerability Assessment: Implement the following skip logic. This is when HIV status is "No, status unknown " on "Is HIV status known?" #510
-VCA Vulnerability Assessment: Implement the following skip logic. This is when HIV status is "Yes, status Negative " on "Is HIV status known?" #509
=> Completed issues

opensrp-ecap-chw/src/ecap/assets/json.form/vca_assessment.json, opensrp-ecap-chw/src/ecap/assets/rule/vca_assessment.yml, opensrp-ecap-chw/src/ecap/assets/rule/vca_vulnerability_assessment_relevance.yml, opensrp-ecap-chw/src/main/java/com/bluecodeltd/ecap/chw/activity/IndexDetailsActivity.java
-VCA Vulnerability Assessment: Implement the following skip logic. This is when HIV status is "No, status unknown " on "Is HIV status known?" #510
-VCA Vulnerability Assessment: Implement the following skip logic. This is when HIV status is "Yes, status Negative " on "Is HIV status known?" #509
=> Work in progress of the following

opensrp-ecap-chw/src/ecap/assets/json.form/hh_screening_entry.json, opensrp-ecap-chw/src/ecap/assets/json.form/vca_screening.json
-Updated the ART number on the household screening form
-Removed the "Does the child/adolescent get drugs to prevent  Tuberculosis( TB Preventive Therapy TPT"
-Question on ART already asked in 1 and ART # already provided should logically pre-fill "Yes" on the ART question in 2. #415
=> Worked on the following issues

opensrp-ecap-chw/src/ecap/assets/json.form/hh_screening_entry.json
Skip logic on viral load issue296, enabled caregiver's gender and DOB
=> Skip logic on viral load issue296, enabled caregiver's gender and DOB

opensrp-ecap-chw/src/ecap/assets/ec_client_fields.json, opensrp-ecap-chw/src/ecap/assets/json.form/household_visitation_for_vca_0_20_years.json, opensrp-ecap-chw/src/ecap/assets/rule/household_visitation_form_0_20.yml, opensrp-ecap-chw/src/main/java/com/bluecodeltd/ecap/chw/dao/IndexPersonDao.java, opensrp-ecap-chw/src/main/java/com/bluecodeltd/ecap/chw/model/Child.java
-Household visitation on safe (Neglect/Exploitation) - Implement the following skip logic #542
-Household visitation on Nutrition (ALL VCA except Under-Five Children)- Implement the following skip logic #541
-Hide the label "Nutrition (ALL VCA except Under-Five Children)". If the VCA is below 5 hide the label on household visitation #540
-Household visitation on Knowledge of HIV/AIDS (10-17 Years Old)- Implement the following skip logic #539
-Household visitation on safe (Physical violence) - Implement the following skip logic #543
=> Resolved the following issues

opensrp-ecap-chw/src/ecap/assets/ec_client_fields.json, opensrp-ecap-chw/src/ecap/assets/json.form/hiv_risk_assessment_under_15_years.json, opensrp-ecap-chw/src/ecap/assets/rule/risk_assessment_under_15.yml, opensrp-ecap-chw/src/main/java/com/bluecodeltd/ecap/chw/dao/HivAssessmentUnder15Dao.java, opensrp-ecap-chw/src/main/java/com/bluecodeltd/ecap/chw/model/HivRiskAssessmentUnder15Model.java
-For a VCA that is 2 to 14 if he or she has never tested or tested negative but has had new exposure since the last test. Screening should continue. #560
-On HIV risk assessment if the VCA is between 2 to 14 the questions "Is the child’s biological mother HIV+ or is her HIV status unknown?", "Are one or both of this child’s biological parents deceased?" and "Has the child been exposed to any HIV risk after the last test (tick all applicable)? Breast Feeding ☐ Child Sexually abused/Raped ☐ Tattoos/Piercing ☐ " are missing and include message toasters "Refer for HIV Testing" if yes is answered to any of the questions above including those already on the app #559
=> Resolved high priority issues of the following

opensrp-ecap-chw/src/ecap/assets/ec_client_fields.json, opensrp-ecap-chw/src/ecap/assets/json.form/household_visitation_for_vca_0_20_years.json, opensrp-ecap-chw/src/ecap/assets/json.form/vca_screening.json, opensrp-ecap-chw/src/ecap/assets/rule/household_visitation_form_0_20.yml
-The fields "How long has a child been on ART? months", "If the child has been on ART for longer than six months, have they submitted a sample for VL(Yes/No)" and "If yes, verify with health facility and indicate the VL result:" are missing on household visitation #589
=> Fixed the missing fields on the Household Visitation of the VCA

opensrp-ecap-chw/src/ecap/assets/ec_client_classification.json, opensrp-ecap-chw/src/ecap/assets/ec_client_fields.json, opensrp-ecap-chw/src/ecap/assets/json.form/family_member.json, opensrp-ecap-chw/src/ecap/assets/json.form/hh_caregiver_assessment.json, opensrp-ecap-chw/src/ecap/assets/json.form/hh_screening_entry.json, opensrp-ecap-chw/src/ecap/assets/rule/caregiver_household_vulnerability_assessment_relevance.yml, opensrp-ecap-chw/src/main/java/com/bluecodeltd/ecap/chw/activity/HouseholdDetails.java
-Currently when a family member is added to a household and this member is above 20 for example and/or does not fall under any of the subpopulations, This member is been added under the VCA register. Ensure this VCA will not be saved under the VCA register Because they do not qualify to be enrolled into the program. #626
-The field "Estimated household expenses" to "Caregiver Vulnerability Assessment" #623
-Fixed the missing and the saving of the caregiver and household vulnerability assessment form
=> Fixed high priority issues of the following

opensrp-ecap-chw/src/ecap/assets/json.form/domain.json
Correction on misspelled word.
=> Correction on misspelled word.

opensrp-ecap-chw/src/ecap/assets/json.form/hiv_risk_assessment_above_15_years.json, opensrp-ecap-chw/src/ecap/assets/json.form/hiv_risk_assessment_under_15_years.json, opensrp-ecap-chw/src/ecap/assets/json.form/household_visitation_for_vca_0_20_years.json, opensrp-ecap-chw/src/main/java/com/bluecodeltd/ecap/chw/activity/HouseholdDetails.java, opensrp-ecap-chw/src/main/res/layout/activity_household_details.xml
-Ensure that feature "Household visitation" 20 years+ is disabled in the next build. We are going to confuse the user who will want to click on it . #646
-The options "Yes or No " on the field "With reference to the age of the child, what is the nutrition status of the child" should just allow the user to enter text for now. #645
=> Fixed the high priority issues of the following

opensrp-ecap-chw/src/ecap/assets/json.form/caregiver_assessment.json, opensrp-ecap-chw/src/ecap/assets/json.form/graduation.json, opensrp-ecap-chw/src/ecap/assets/json.form/hh_caregiver_assessment.json, opensrp-ecap-chw/src/ecap/assets/json.form/vca_screening.json
Resolved issue 669: Disable All AGYW questions for male VCA.
Additional relevance on FSW question
=> Resolved issue 669: Disable All AGYW questions for male VCA.

opensrp-ecap-chw/src/ecap/assets/ec_client_fields.json, opensrp-ecap-chw/src/ecap/assets/json.form/case_status.json, opensrp-ecap-chw/src/main/java/com/bluecodeltd/ecap/chw/activity/IndexDetailsActivity.java, opensrp-ecap-chw/src/main/java/com/bluecodeltd/ecap/chw/dao/VCAScreeningDao.java, opensrp-ecap-chw/src/main/java/com/bluecodeltd/ecap/chw/model/MotherIndexModel.java, opensrp-ecap-chw/src/main/java/com/bluecodeltd/ecap/chw/model/VcaScreeningModel.java, opensrp-ecap-chw/src/main/res/layout/vca_content.xml, opensrp-ecap-chw/src/main/res/menu/menu.xml
-Create a new feature OVC deregistration feature. #666
-HIV Risk Assessment is assessed only to the HIV negative VCA`s
=> Client Feedback Issues

opensrp-ecap-chw/src/ecap/assets/ec_client_fields.json, opensrp-ecap-chw/src/ecap/assets/json.form/hh_caregiver_assessment.json, opensrp-ecap-chw/src/ecap/assets/json.form/hh_screening_entry.json, opensrp-ecap-chw/src/ecap/assets/json.form/household_visitation_for_caregiver.json, opensrp-ecap-chw/src/main/java/com/bluecodeltd/ecap/chw/activity/HouseholdDetails.java, opensrp-ecap-chw/src/main/java/com/bluecodeltd/ecap/chw/dao/CaregiverAssessmentDao.java, opensrp-ecap-chw/src/main/java/com/bluecodeltd/ecap/chw/dao/CaregiverVisitationDao.java, opensrp-ecap-chw/src/main/java/com/bluecodeltd/ecap/chw/model/CaregiverAssessmentModel.java, opensrp-ecap-chw/src/main/java/com/bluecodeltd/ecap/chw/model/CaregiverVisitationModel.java, opensrp-ecap-chw/src/main/java/com/bluecodeltd/ecap/chw/util/Constants.java
-Editing/saving of the caregiver vulnerability assessment and caregiver household visitation forms
=> Editting and saving of data

opensrp-ecap-chw/src/ecap/assets/ec_client_fields.json, opensrp-ecap-chw/src/ecap/assets/json.form/hiv_risk_assessment_above_15_years.json, opensrp-ecap-chw/src/ecap/assets/json.form/hiv_risk_assessment_under_15_years.json, opensrp-ecap-chw/src/ecap/assets/json.form/household_visitation_for_vca_0_20_years.json, opensrp-ecap-chw/src/ecap/assets/json.form/referral.json, opensrp-ecap-chw/src/ecap/assets/json.form/vca_assessment.json, opensrp-ecap-chw/src/ecap/assets/json.form/vca_screening.json, opensrp-ecap-chw/src/main/java/com/bluecodeltd/ecap/chw/dao/HivAssessmentAbove15Dao.java, opensrp-ecap-chw/src/main/java/com/bluecodeltd/ecap/chw/dao/HivAssessmentUnder15Dao.java, opensrp-ecap-chw/src/main/java/com/bluecodeltd/ecap/chw/dao/ReferralDao.java, opensrp-ecap-chw/src/main/java/com/bluecodeltd/ecap/chw/dao/VcaAssessmentDao.java, opensrp-ecap-chw/src/main/java/com/bluecodeltd/ecap/chw/model/HivRiskAssessmentAbove15Model.java, opensrp-ecap-chw/src/main/java/com/bluecodeltd/ecap/chw/model/HivRiskAssessmentUnder15Model.java, opensrp-ecap-chw/src/main/java/com/bluecodeltd/ecap/chw/model/ReferralModel.java, opensrp-ecap-chw/src/main/java/com/bluecodeltd/ecap/chw/model/VcaAssessmentModel.java
-Vca vulnerability Assessment
-Referral 
-Vca household visitation
-Hiv risk assessment
=> Name and the date of the caseworker who last  edited information on the following forms

opensrp-ecap-chw/src/ecap/assets/ec_client_fields.json, opensrp-ecap-chw/src/ecap/assets/json.form/hiv_risk_assessment_above_15_years.json, opensrp-ecap-chw/src/ecap/assets/json.form/hiv_risk_assessment_under_15_years.json, opensrp-ecap-chw/src/ecap/assets/json.form/household_visitation_for_vca_0_20_years.json, opensrp-ecap-chw/src/ecap/assets/json.form/referral.json, opensrp-ecap-chw/src/ecap/assets/json.form/vca_assessment.json, opensrp-ecap-chw/src/ecap/assets/json.form/vca_screening.json, opensrp-ecap-chw/src/main/java/com/bluecodeltd/ecap/chw/activity/IndexDetailsActivity.java, opensrp-ecap-chw/src/main/java/com/bluecodeltd/ecap/chw/dao/HivAssessmentAbove15Dao.java, opensrp-ecap-chw/src/main/java/com/bluecodeltd/ecap/chw/dao/HivAssessmentUnder15Dao.java, opensrp-ecap-chw/src/main/java/com/bluecodeltd/ecap/chw/dao/IndexPersonDao.java, opensrp-ecap-chw/src/main/java/com/bluecodeltd/ecap/chw/dao/ReferralDao.java, opensrp-ecap-chw/src/main/java/com/bluecodeltd/ecap/chw/dao/VCAScreeningDao.java, opensrp-ecap-chw/src/main/java/com/bluecodeltd/ecap/chw/dao/VcaAssessmentDao.java, opensrp-ecap-chw/src/main/java/com/bluecodeltd/ecap/chw/dao/VcaVisitationDao.java, opensrp-ecap-chw/src/main/java/com/bluecodeltd/ecap/chw/fragment/ProfileOverviewFragment.java, opensrp-ecap-chw/src/main/java/com/bluecodeltd/ecap/chw/model/Child.java, opensrp-ecap-chw/src/main/java/com/bluecodeltd/ecap/chw/model/HivRiskAssessmentAbove15Model.java, opensrp-ecap-chw/src/main/java/com/bluecodeltd/ecap/chw/model/HivRiskAssessmentUnder15Model.java, opensrp-ecap-chw/src/main/java/com/bluecodeltd/ecap/chw/model/ReferralModel.java, opensrp-ecap-chw/src/main/java/com/bluecodeltd/ecap/chw/model/VcaAssessmentModel.java, opensrp-ecap-chw/src/main/java/com/bluecodeltd/ecap/chw/model/VcaScreeningModel.java, opensrp-ecap-chw/src/main/java/com/bluecodeltd/ecap/chw/model/VcaVisitationModel.java, opensrp-ecap-chw/src/main/res/layout/fragment_overview.xml
-Vca vulnerability Assessment
-Referral
-Vca household visitation
-Hiv risk assessment
=> Phone number of the caseworker who last edited information shows on the vca profile and on the following forms

opensrp-ecap-chw/src/ecap/assets/ec_client_fields.json, opensrp-ecap-chw/src/main/java/com/bluecodeltd/ecap/chw/dao/HouseholdDao.java, opensrp-ecap-chw/src/main/java/com/bluecodeltd/ecap/chw/model/Household.java
Prepopulation on Household form
=> Prepopulation of Consent on HH Form

opensrp-ecap-chw/src/ecap/assets/ec_client_fields.json, opensrp-ecap-chw/src/ecap/assets/json.form/hh_screening_entry.json, opensrp-ecap-chw/src/ecap/assets/rule/hh_screening_calculation.yml, opensrp-ecap-chw/src/main/java/com/bluecodeltd/ecap/chw/dao/HouseholdDao.java, opensrp-ecap-chw/src/main/java/com/bluecodeltd/ecap/chw/model/Household.java, opensrp-ecap-chw/src/main/java/com/bluecodeltd/ecap/chw/model/VcaScreeningModel.java
Household Screening: Audit trail
=> Household Screening: Audit trail

opensrp-ecap-chw/src/ecap/assets/json.form/child.json, opensrp-ecap-chw/src/ecap/assets/json.form/family_member.json, opensrp-ecap-chw/src/ecap/assets/json.form/hh_screening_entry.json, opensrp-ecap-chw/src/ecap/assets/json.form/mother_index.json, opensrp-ecap-chw/src/main/java/com/bluecodeltd/ecap/chw/dao/CaregiverDao.java, opensrp-ecap-chw/src/main/java/com/bluecodeltd/ecap/chw/model/Caregiver.java, opensrp-ecap-chw/src/main/res/layout/vca_content.xml
-Change the field label “Plot Number, Village or Street” to “Home Address” For the purpose of consistency.
-Include the field “ART Number”, this should be below the field “Mother’s HIV Status”. ART number should not be a required field.
-On adding a biological child once the “Date of birth” has been added. The age for that member also shows, similar to how this has been implemented on index VCA screening.
=> Fix issues in the mother and child form

opensrp-ecap-chw/src/ecap/assets/ec_client_classification.json, opensrp-ecap-chw/src/ecap/assets/ec_client_fields.json, opensrp-ecap-chw/src/ecap/assets/json.form/hh_caregiver_assessment.json, opensrp-ecap-chw/src/ecap/assets/json.form/hh_hiv_assessment_caregiver.json, opensrp-ecap-chw/src/main/java/com/bluecodeltd/ecap/chw/activity/HouseholdDetails.java, opensrp-ecap-chw/src/main/java/com/bluecodeltd/ecap/chw/adapter/ChildrenAdapter.java, opensrp-ecap-chw/src/main/java/com/bluecodeltd/ecap/chw/dao/CaregiverHivAssessmentDao.java, opensrp-ecap-chw/src/main/java/com/bluecodeltd/ecap/chw/model/CaregiverHivAssessmentModel.java, opensrp-ecap-chw/src/main/java/com/bluecodeltd/ecap/chw/util/Constants.java, opensrp-ecap-chw/src/main/res/layout/activity_household_details.xml
-Launching, saving and editing of the Hiv Risk Assessment for caregiver in the household profile
-"Result of most recent viral load test” and “Date of last viral load test" fields  in the Caregiver Vulnerability Assessment form are now editable
=> Resolved the following

opensrp-ecap-chw/src/ecap/assets/ec_client_fields.json, opensrp-ecap-chw/src/ecap/assets/json.form/hh_screening.json, opensrp-ecap-chw/src/ecap/assets/json.form/hh_screening_entry.json, opensrp-ecap-chw/src/ecap/assets/json.form/vca_screening.json, opensrp-ecap-chw/src/ecap/assets/rule/referral_relevance.yml
-Display enrollment details on VCA profile for VCAs entered from the household. Also add a Caregiver's relationship to the VCA on the Household screening form #820
-The field short term emergency support is not triggering the date provided field #829
-Back data entry date for the vca in household and vca screening forms
=> Fixed the following issues

opensrp-ecap-chw/src/ecap/assets/ec_client_fields.json, opensrp-ecap-chw/src/ecap/assets/json.form/we_services_vca.json, opensrp-ecap-chw/src/main/java/com/bluecodeltd/ecap/chw/activity/IndexDetailsActivity.java, opensrp-ecap-chw/src/main/java/com/bluecodeltd/ecap/chw/dao/MuacDao.java, opensrp-ecap-chw/src/main/java/com/bluecodeltd/ecap/chw/dao/WeServiceVcaDao.java, opensrp-ecap-chw/src/main/java/com/bluecodeltd/ecap/chw/model/WeServiceVcaModel.java
WE Service Form VCA - Complete
=> WE Service Form VCA - Complete

opensrp-ecap-chw/src/ecap/assets/json.form/grad.json, opensrp-ecap-chw/src/ecap/assets/rule/grad_calculation.yml
=> Change virally suppressed calculation and only display in benchmark 2 if vca status is positive

opensrp-ecap-chw/src/main/java/com/bluecodeltd/ecap/chw/adapter/VisitAdapter.java, opensrp-ecap-chw/src/main/res/layout/single_vca_visit.xml
=> Show a summary of revisits, with an emphasis on information regarding VCA HIV status

opensrp-ecap-chw/src/ecap/assets/json.form/household_case_status.json, opensrp-ecap-chw/src/ecap/assets/json.form/household_visitation_for_vca_0_20_years.json, opensrp-ecap-chw/src/ecap/assets/json.form/service_report_vca.json, opensrp-ecap-chw/src/ecap/assets/rule/family_member_calculation.yml, opensrp-ecap-chw/src/main/java/com/bluecodeltd/ecap/chw/activity/HouseholdCasePlanActivity.java, opensrp-ecap-chw/src/main/java/com/bluecodeltd/ecap/chw/activity/HouseholdDetails.java
- Enroll family members without a subpopulation between the ages of 0 and 17 as active
- Add an adherence support option on the VCA service report form
- Add household case status relevance for closing a case
=> Fixed the following:
